### PR TITLE
Fix entity interactions

### LINKED ISSUE #41: [Bug]: Entities should have a tag to allow them to bypass greifing check
### Bug Description

-

### How to Reproduce?

_No response_

### Expected Behavior

_No response_

### Version

-

### Mod Loader Version

-

### Mod Loader

_No response_

### Logs or additional context

_No response_

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

### PR DESCRIPTION
**Pull request by CodexAdrian**
This PR adds a few more tags to make it easier to disable protections on certain interactions
In addition, it also moves away from using exclusive instanceof checks to use tag checks for better mod compat

### CODE REVIEW

File: common/src/main/java/earth/terrarium/cadmus/Cadmus.java [hunk 1]
```diff
@@ -31,7 +32,16 @@ public class Cadmus {
 
     public static int FORCE_LOADED_CHUNK_COUNT;
     public static final TagKey<Block> ALLOWS_CLAIM_INTERACTIONS = TagKey.create(Registries.BLOCK, new ResourceLocation(MOD_ID, "allows_claim_interactions"));
+    public static final TagKey<Item> ALLOWS_CLAIM_PICKUP = TagKey.create(Registries.ITEM, new ResourceLocation(MOD_ID, "allows_claim_pickup"));
     public static final TagKey<EntityType<?>> ALLOWS_CLAIM_INTERACTIONS_ENTITIES = TagKey.create(Registries.ENTITY_TYPE, new ResourceLocation(MOD_ID, "allows_claim_interactions"));
+    public static final TagKey<EntityType<?>> ALLOWS_CLAIM_DAMAGE_ENTITIES = TagKey.create(Registries.ENTITY_TYPE, new ResourceLocation(MOD_ID, "allows_claim_damage"));
+    public static final TagKey<EntityType<?>> CAN_GRIEF_ENTITIES = TagKey.create(Registries.ENTITY_TYPE, new ResourceLocation(MOD_ID, "can_grief"));
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/Cadmus.java]: Should be moved to a `ModEntityTypeTags` class to not clutter main. ex. https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/common/src/main/java/earth/terrarium/adastra/common/tags/ModEntityTypeTags.java

File: common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java [hunk 2]
```diff
@@ -132,16 +134,17 @@ public boolean canInteractWithBlock(Level level, BlockPos pos, InteractionType t
...
-                Block block = level.getBlockState(pos).getBlock();
-                if (block instanceof DoorBlock || block instanceof TrapDoorBlock) {
+                BlockState state = level.getBlockState(pos);
+                Block block = state.getBlock();
+                if (state.is(BlockTags.DOORS) || state.is(BlockTags.TRAPDOORS)) {
                     return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.USE_DOORS);
                 }
 
-                if (block instanceof AbstractChestBlock<?>) {
+                if (block instanceof AbstractChestBlock<?> || state.is(Cadmus.FABRIC_CHESTS) || state.is(Cadmus.FORGE_CHESTS)) {
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java]: Use a common cadmus:chest tag and just include the platform tags as optional tags within it

File: common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java [hunk 3]
```diff
@@ -132,16 +134,17 @@ public boolean canInteractWithBlock(Level level, BlockPos pos, InteractionType t
...
                     return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.USE_CHESTS);
                 }
 
-                if (block instanceof LeverBlock || block instanceof ButtonBlock || block instanceof PressurePlateBlock) {
+                if (state.is(BlockTags.PRESSURE_PLATES) || state.is(BlockTags.BUTTONS) || block instanceof LeverBlock || state.is(Cadmus.FABRIC_LEVER) || state.is(Cadmus.FORGE_LEVER)) {
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java]: Use a common cadmus:redstone tag and just include the platform tags as optional tags within it

File: common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java [hunk 4]
```diff
@@ -220,6 +224,9 @@ public boolean canEntityGrief(Level level, BlockPos pos, @NotNull Entity entity)
 
     @Override
     public boolean canPickupItem(Level level, BlockPos pos, ItemEntity item, @NotNull Entity picker) {
+        if (item.getItem().is(Cadmus.ALLOWS_CLAIM_PICKUP)) {
+            return true;
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java]: Use a 1 line return statement for short checks like these. ex. `if(item.getItem().is(Cadmus.ALLOWS_CLAIM_PICKUP)) return;`
It makes the code cleaner imo especially when there's a lot of consecutive checks

File: common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java [hunk 5]
```diff
@@ -173,24 +176,22 @@ public boolean canInteractWithEntity(Level level, Entity entity, @NotNull Player
...
+                    return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.PVP);
                 }
 
-                if (entity.getType().getCategory() == MobCategory.MONSTER || entity instanceof Monster) {
+                if (entity.getType().getCategory() == MobCategory.MISC) {
+                    return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.ENTITY_DAMAGE);
+                } else if (entity.getType().getCategory().isFriendly()) {
+                    return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.CREATURE_DAMAGE);
+                } else {
                     return AdminClaimHandler.getBooleanFlag(server, id, ModFlags.MONSTER_DAMAGE);
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java:172]: Change the order so that it checks living, then monster, and else normal entity damage

**Review by AlexNijjar — CHANGES_REQUESTED** [review]

File: common/src/main/resources/assets/data/cadmus/tags/blocks/door_like.json [hunk 6]
```diff
@@ -0,0 +1,7 @@
+{
+  "replace": false,
```
Comment (AlexNijjar) [inline common/src/main/resources/assets/data/cadmus/tags/blocks/door_like.json]: replace is false by default so it's not needed for any of the tags

File: common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java [hunk 7]
```diff
@@ -9,22 +9,24 @@
...
 import earth.terrarium.cadmus.common.compat.prometheus.PrometheusIntegration;
+import earth.terrarium.cadmus.common.util.ModEntityTags;
 import earth.terrarium.cadmus.common.util.ModGameRules;
 import earth.terrarium.cadmus.common.util.ModUtils;
 import net.minecraft.core.BlockPos;
 import net.minecraft.server.MinecraftServer;
 import net.minecraft.server.level.ServerLevel;
 import net.minecraft.world.entity.Entity;
-import net.minecraft.world.entity.MobCategory;
+import net.minecraft.world.entity.LivingEntity;
```
Comment (AlexNijjar) [inline common/src/main/java/earth/terrarium/cadmus/common/claims/ClaimApiImpl.java]: remove unused imports

**Review by AlexNijjar — CHANGES_REQUESTED** [review]

**Review by AlexNijjar — APPROVED** [review]
